products/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from .views import ProductDetailView, ProductListView, VariationListView

urlpatterns = [
    # Examples:
    # url(r'^$', 'newsletter.views.home', name='home'),
    url(r'^$', ProductListView.as_view(), name='products'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='product_inventory'),
    # url(r'^(?P<id>\d+)', 'products.views.product_detail_view_func', name='product_detail_function'),
]

products/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.utils.text import slugify

# Create your models here.

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self, *args, **kwargs):
        return self.get_queryset().active()


class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    active = models.BooleanField(default=True)

    objects = ProductManager()

    def get_absolute_url(self):
        # return "products/%s" % (self.pk)
        return reverse("product_detail", kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.title


class Variation(models.Model):
    product = models.ForeignKey(Product)
    title = models.CharField(max_length=120)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    sale_price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
    active = models.BooleanField(default=True)
    inventory = models.IntegerField(null=True, blank=True) # refer none == unlimited amount

    def __unicode__(self):
        return self.title

    def get_price(self):
        if self.sale_price is not None:
            return self.sale_price
        else:
            return self.price

    def get_absolute_url(self):
        return self.product.get_absolute_url()

def product_post_saved_receiver(sender, instance, created, *args, **kwargs):
    product = instance
    variations = product.variation_set.all()
    # variations = Variation.objects.filter(product=product)

    if variations.count() == 0:
        new_vari = Variation()
        new_vari.product = product
        new_vari.title = 'Default'
        new_vari.price = product.price
        new_vari.save()

post_save.connect(product_post_saved_receiver, sender=Product)


def image_upload_to(instance, filename):
    title = instance.product.title
    slug = slugify(title)
    basename, file_extension = filename.split('.')
    new_filename = "%s-%s.%s" % (slug, instance.id, file_extension)
    return "products/%s/%s" % (slug, new_filename)

class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to=image_upload_to)

    def __unicode__(self):
        return self.product.title

# Product Category

products/forms.py
from django import forms

from django.forms.models import modelformset_factory

from .models import Variation


class VariationInventoryForm(forms.ModelForm):
    class Meta:
        model = Variation
        fields = [
            'title',
            'price',
            'sale_price',
            'inventory',
            'active',
        ]


VariationInventoryFormSet = modelformset_factory(Variation, form=VariationInventoryForm, extra=1)

products/views.py
from django.contrib import messages
from django.db.models import Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

# Create your views here.

from .mixins import StaffRequiredMixins
from .forms import VariationInventoryFormSet
from .models import Product, Variation


class VariationListView(StaffRequiredMixins, ListView):
    model = Variation
    queryset = Variation.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(VariationListView, self).get_context_data(*args, **kwargs)
        context['formset'] = VariationInventoryFormSet(queryset=self.get_queryset())
        return context

    def get_queryset(self, *args, **kwargs):
        product_pk = self.kwargs.get('pk')
        if product_pk:
            product = get_object_or_404(Product, pk=product_pk)
            queryset = Variation.objects.filter(product=product)
        return queryset

    def post(self, request, *args, **kwargs):
        formset = VariationInventoryFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save(commit=False)
            for form in formset:
                new_item = form.save(commit=False)
                if new_item.title:
                    product_pk = self.kwargs.get('pk')
                    product = get_object_or_404(Product, pk=product_pk)
                    new_item.product = product
                    new_item.save()

            messages.success(request, 'Your inventory and pricing has been updated!')
            return redirect('products')
        raise Http404

class ProductListView(ListView):
    model = Product
    queryset = Product.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        context['now'] = timezone.now()
        context['query'] = self.request.GET.get('q')
        print context
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(ProductListView, self).get_queryset(*args, **kwargs)
        query = self.request.GET.get('q')
        if query:
            qs = self.model.objects.filter(
                Q(title__icontains=query) |
                Q(description__icontains=query)
            )
            try:
                qs2 = self.model.objects.filter(
                    Q(price=query)
                )
                qs = (qs | qs2).distinct()
            except:
                pass
        return qs


class ProductDetailView(DetailView):
    model = Product
# template_name = 'product.html'


def product_detail_view_func(request, id):
    # product_instance = Product.objects.get(id=id)
    product_instance = get_object_or_404(Product, id=id)
    template = 'products/product_detail.html'
    context = {
        'object': product_instance
    }
    return render(request, template, context)

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row">

    <div class="col-sm-8">
        <h2>{{ object.title }}</h2>
        {% if object.productimage_set.count > 0 %}
        <div>
            {% for img in object.productimage_set.all %}
            <img class="img-responsive" src=" {{ img.image.url }}"/>
            {% endfor %}
        </div>
        {% endif %}
        <p class="lead">
            {{ object.description }}
        </p>
    </div>

    <!-- Product sidebar -->
    <div class="col-sm-4">
        <h3>{{ object.price }}</h3>
        {% if object.variation_set.count > 1 %}
        <select class="form-control">
            {% for vari_obj in object.variation_set.all %}
            <option value="{{ vari_obj.id }}">{{ vari_obj }}</option>
            {% endfor %}
        </select>
        {% endif %}
        <br/>
        <a href="#">Add to Cart</a>
        <br/>
        <hr/>
        <h4>Related Products</h4>
    </div>
    <!-- end product sidebar -->
</div>
{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}

<!--{{ object_list }}-->

<table class="table">
{% for object in object_list %}

<tr>
    <!--<td><a href="{% url 'product_detail' pk=object.pk%}"> {{ object.title }}</a></td>-->
    <td><a href="{{ object.get_absolute_url }}"> {{ object.title }}</a></td>
</tr>

{% endfor %}
</table>
<!--{{ now }}-->

<!--{{ user }}-->

{% endblock %}

products/templates/products/variation_list.html
{% extends 'base.html' %}

{% block content %}

<!--{{ object_list }}-->

<table class="table">
{% for object in object_list %}

<tr>
    <!--<td><a href="{% url 'product_detail' pk=object.pk%}"> {{ object.title }}</a></td>-->
    <td><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></td><td>{{ object.inventory }}</td>
</tr>

{% endfor %}
</table>

<form method="POST" action="">{% csrf_token %}
    {{ formset.management_form }}

    {% for form in formset %}

    {{ form.instance.product.title }}
    {{ form.instance.title }}
    {{ form.as_p }}

    {% endfor %}

    <input type="submit" value="Update" class="btn">
</form>

{% endblock %}